robot:
  ip: 192.168.15.82
  control_port: 2002
  command_port: 2000
  status_port: 2001

paths:
  #ROBOT related UDS sockets
  command_socket: /tmp/robot_forward_command.sock #G and some M codes go here (G1, M204, M17 etc)
  control_socket: /tmp/robot_forward_control.sock #Control related M codes go here (M2, M100, M25 etc)
  status_socket: /tmp/robot_forward_status.sock #For M123 status check

unix:
  path: /tmp

timeouts:
  socket: 3.0
  heartbeat:
    enabled: true
    payload: "snd 000"

timestamps:
  enabled: true          # whether to inject timestamp
  mode: local              # utc | local
  field: "timestamp"    # JSON field name
